- pipeline.id: seoul-pipeline
  path.config: /usr/share/logstash/pipeline/seoul_air_pollution.conf

- pipeline.id: india-pipeline
path.config: /usr/share/logstash/pipeline/india_air_pollution.conf

- pipeline.id: mexico-pipeline
  path.config: /usr/share/logstash/pipeline/mexico_air_pollution.conf