input {
   file {
      path => "/usr/share/logstash/data/india_air_pollution_daily.csv"
      start_position => "beginning"
   }
}
filter {
   grok {
      match => {
         "message" => "%{WORD:city},%{DATE:timestamp},%{NUMBER:pm25},%{NUMBER:pm10},%{NUMBER:no2},%{NUMBER:nox},%{NUMBER:nh3},%{NUMBER:co},%{NUMBER:so2},%{NUMBER:o3},%{NUMBER:benzene},%{NUMBER:toluene},%{NUMBER:xylene},%{NUMBER:aqi},%{GREEDYDATA:aqi_bucket}"
      }
   }
   date {
        match => [ "timestamp", "yyyy-MM-dd" ]
        target => "timestamp_filter"
   }
   mutate {
      convert => {
         "pm25" => "float"
      }
   }
   mutate {
      convert => {
         "pm10" => "float"
      }
   }
   mutate {
      convert => {
         "no2" => "float"
      }
   }
   mutate {
      convert => {
         "nox" => "float"
      }
   }
   mutate {
      convert => {
         "nh3" => "float"
      }
   }
   mutate {
      convert => {
         "co" => "float"
      }
   }
   mutate {
      convert => {
         "so2" => "float"
      }
   }
   mutate {
      convert => {
         "o3" => "float"
      }
   }
   mutate {
      convert => {
         "benzene" => "float"
      }
   }
   mutate {
      convert => {
         "toluene" => "float"
      }
   }
   mutate {
      convert => {
         "xylene" => "float"
      }
   }
   mutate {
      convert => {
         "aqi" => "float"
      }
   }
}
output {
	elasticsearch {
		hosts => "http://elasticsearch:9200"
		index => "india_ap"
		template => "/usr/share/logstash/template/india_air_pollution_template.json"
		template_name => "india_ap_elastic"
		template_overwrite => true
		manage_template => true
	}
}