input {
   file {
      path => "/usr/share/logstash/data/mexico_air_pollution_daily.csv"
      start_position => "beginning"
   }
}
filter {
   csv {
      separator => ","
      columns => [
         "timestamp_filter", "station_id", "pm25", "pm10", "nox", "o3", "co", "hr", "no", "no2",
         "tmp", "benzene", "ch4", "cn", "co2", "h2s", "hcnm", "hct", "hri", "iuv", "pb", "pp", 
         "pst", "rs", "tmpi", "uva", "xylene"
      ]
      skip_header => true
   }
   mutate {
      convert => {
         "station_id" => "integer"
         "pm25" => "float"
         "pm10" => "float"
         "nox" => "float"
         "o3" => "float" 
         "co" => "float"
         "hr" => "float"
         "no" => "float"
         "no2" => "float"
         "tmp" => "float"
         "benzene" => "float"                 
         "ch4" => "float"
         "cn" => "float"
         "co2" => "float"
         "h2s" => "float"
         "hcnm" => "float"
         "hct" => "float"
         "hri" => "float"
         "iuv" => "float"
         "pb" => "float"
         "pp" => "float"
         "pst" => "float"
         "rs" => "float"
         "tmpi" => "float"
         "uva" => "float"
         "xylene" => "float"
      }
   }
   mutate {
      remove_field => ["message", "path"]
   }
}
output {
	elasticsearch {
		hosts => "http://elasticsearch:9200"
		index => "mexico_ap"
		template => "/usr/share/logstash/template/mexico_air_pollution_template.json"
		template_name => "mexico_ap_elastic"
		template_overwrite => true
		manage_template => true
	}
}