input {
   file {
      path => "/usr/share/logstash/data/mexico_air_pollution_daily.csv"
      start_position => "beginning"
   }
}
filter {
   grok {
      match => {
         "message" => "%{DATE:timestamp},%{NUMBER:station_id},%{NUMBER:pm25},%{NUMBER:pm10},%{NUMBER:nox},%{NUMBER:o3},%{NUMBER:co},%{NUMBER:hr},%{NUMBER:no},%{NUMBER:no2},%{NUMBER:tmp},%{NUMBER:benzene},%{NUMBER:ch4},%{NUMBER:cn},%{NUMBER:co2},%{NUMBER:h2s},%{NUMBER:hcnm},%{NUMBER:hct},%{NUMBER:hri},%{NUMBER:iuv},%{NUMBER:pb},%{NUMBER:pp},%{NUMBER:pst},%{NUMBER:rs},%{NUMBER:tmpi},%{NUMBER:uva},%{NUMBER:xylene}"
      }
   }
   date {
        match => [ "timestamp", "yyyy-MM-dd" ]
        target => "timestamp_filter"
   }
   mutate {
      convert => {
         "station_id" => "integer"
      }
   }
   mutate {
      convert => {
         "pm25" => "float"
      }
   }
   mutate {
      convert => {
         "pm10" => "float"
      }
   }
      mutate {
      convert => {
         "nox" => "float"
      }
   }
   mutate {
      convert => {
         "no2" => "float"
      }
   }
      mutate {
      convert => {
         "tmp" => "float"
      }
   }
      mutate {
      convert => {
         "hr" => "float"
      }
   }
      mutate {
      convert => {
         "no" => "float"
      }
   }
   mutate {
      convert => {
         "co" => "float"
      }
   }
   mutate {
      convert => {
         "o3" => "float"
      }
   }
   mutate {
      convert => {
         "benzene" => "float"
      }
   }
   mutate {
      convert => {
         "xylene" => "float"
      }
   }
      mutate {
      convert => {
         "ch4" => "float"
      }
   }
      mutate {
      convert => {
         "cn" => "float"
      }
   }
      mutate {
      convert => {
         "co2" => "float"
      }
   }
      mutate {
      convert => {
         "h2s" => "float"
      }
   }
      mutate {
      convert => {
         "hcnm" => "float"
      }
   }
      mutate {
      convert => {
         "hct" => "float"
      }
   }
      mutate {
      convert => {
         "hri" => "float"
      }
   }
      mutate {
      convert => {
         "iuv" => "float"
      }
   }
      mutate {
      convert => {
         "pb" => "float"
      }
   }
      mutate {
      convert => {
         "pp" => "float"
      }
   }
      mutate {
      convert => {
         "pst" => "float"
      }
   }
      mutate {
      convert => {
         "rs" => "float"
      }
   }
      mutate {
      convert => {
         "tmpi" => "float"
      }
   }
      mutate {
      convert => {
         "uva" => "float"
      }
   }
}
output {
	elasticsearch {
		hosts => "http://elasticsearch:9200"
		index => "mexico_ap"
		template => "/usr/share/logstash/template/mexico_air_pollution_template.json"
		template_name => "mexico_ap_elastic"
		template_overwrite => true
		manage_template => true
	}
}