input {
   file {
      path => "/usr/share/logstash/data/seoul_air_pollution_hourly.csv"
      start_position => "beginning"
   }
}
filter {
   grok {
      match => {
         "message" => "%{CUSTOM_DATE:timestamp},%{INT:station_code},\"(?<address>[^\"]+)\",%{NUMBER:latitude},%{NUMBER:longitude},%{NUMBER:so2},%{NUMBER:no2},%{NUMBER:o3},%{NUMBER:co},%{NUMBER:pm10},%{NUMBER:pm25}"
      }
      pattern_definitions => {
         "CUSTOM_DATE" => "%{YEAR}-%{MONTHNUM}-%{MONTHDAY} %{HOUR}:%{MINUTE}"
      }
   }
   date {
        match => [ "timestamp", "yyyy-MM-dd HH:mm" ]
        target => "timestamp_filter"
   }
   mutate {
      convert => {
         "station_code" => "integer"
         "latitude" => "float"
         "longitude" => "float"
         "so2" => "float"
         "no2" => "float"
         "o3" => "float"
         "co" => "float"
         "pm10" => "float"
         "pm25" => "float"
      }
   }
   mutate {
      remove_field => ["message", "path"]
   }
}
output {
	elasticsearch {
		hosts => "http://elasticsearch:9200"
		index => "seoul_ap"
		template => "/usr/share/logstash/template/seoul_air_pollution_template.json"
		template_name => "seoul_ap_elastic"
		template_overwrite => true
		manage_template => true
	}
}