input {
   file {
      path => "/usr/share/logstash/data/india_air_pollution_daily.csv"
      start_position => "beginning"
   }
}
filter {
  csv {
    separator => ","
    columns => [
      "city", "timestamp_filter", "pm25", "pm10", "no", "no2", "nox", "nh3", "co", "so2", "o3",
      "benzene", "toluene", "xylene", "aqi", "aqi_bucket"
    ]
    skip_header => true
  }
  mutate {
    convert => {
      "pm25" => "float"
      "pm10" => "float"
      "no" => "float"
      "no2" => "float"
      "nox" => "float"
      "nh3" => "float"
      "co" => "float"
      "so2" => "float"
      "o3" => "float"
      "benzene" => "float"
      "toluene" => "float"
      "xylene" => "float"
      "aqi" => "float"
    }
  }
  mutate {
    remove_field => ["message", "path"]
  }
}
output {
	elasticsearch {
		hosts => "http://elasticsearch:9200"
		index => "india_ap"
		template => "/usr/share/logstash/template/india_air_pollution_template.json"
		template_name => "india_ap_elastic"
		template_overwrite => true
		manage_template => true
	}
}